---
title: "Final Project"
author: "Iman Byndloss, Brock Keller, and Rachel Williams"
date: "2025-02-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(dplyr)
library(tidyverse)
library(moments)
library(ggplot2)
library(lubridate)
library(readxl)
library(FSA)
library(lme4)
library(lmerTest)

```


```{r}
#NC air data from EPA
Air_Data_NC <- read.csv("NC_Air_Data_Project.csv")
```



```{r}
#making a plot for first assignment
#annual range in concentrations of select chemical in each site
unique(Air_Data_NC$SITE_ID)
#setting concentrations to be numeric

Air_Data_NC <- Air_Data_NC %>% 
  mutate(across(c(Week, Year, Ca, Cl, HNO3, HNO3.PPB, K, Mg, Na, NH4, NO3, SO2, SO2.PPB, SO4, TNO3,), as.numeric))

#Changing SITE_ID to name of actual town
Air_Data_NC <- Air_Data_NC %>% 
  mutate(SITE_ID = case_when(
    SITE_ID == "BFT142" ~ "Beaufort",
    SITE_ID == "CND125" ~ "Candor",
    SITE_ID == "COW137" ~ "Coweeta",
    SITE_ID == "DUK008" ~ "Duke Forest",
    SITE_ID == "PNF126" ~ "Cranberry"
  ))


#filtering for just 2022
Air_Data_2022 <- Air_Data_NC %>% 
  filter(Year == "2022")

#checking how variables are stored. Looks good
str(Air_Data_2022$SO4)


#grouping by SITE_ID and getting summary statistics
Air_Summary_2022_SO4 <- Air_Data_2022 %>% 
  group_by(SITE_ID) %>% 
  summarize(mean = mean(SO4, na.rm = TRUE),
            sd = sd(SO4, na.rm = TRUE)) %>% 
  ungroup()

#making plot
jpeg(filename = "ByndlossIKellerBWilliamsRFig1.jpeg", 
     width = 2400, height = 1800, res = 300)

SO4_2022_plot <- ggplot()+
  geom_errorbar(data = Air_Summary_2022_SO4, na.rm = TRUE,
                aes(x = SITE_ID, 
                    ymin = mean - sd,
                    ymax = mean + sd,
                    color = SITE_ID),
                width = 0.1, size = 1)+
  geom_jitter(data = Air_Data_2022, na.rm = TRUE,
              aes(x = SITE_ID, y = SO4, 
                  color = SITE_ID),
              alpha = 0.8, size = 0.5)+
  geom_point(data = Air_Summary_2022_SO4, na.rm = TRUE,
             aes(x = SITE_ID, y = mean,
                 color = SITE_ID),
             SIZE = 3)+
  labs(title = "Concentrations of SO4 by Site in 2022",
       x = "Site",
       y = "Weekly Mean SO4 Concentration (ug/m^3)",
       caption = "Figure 1: Figure showing mean weekly SO4 air concentration \n in 2022 across five EPA air monitoring sites in North Carolina.")+
  theme_bw()+ 
  theme(plot.caption = 
      element_text(hjust =  0.5, size = 10))

print(SO4_2022_plot)

dev.off()
```


```{r}

#Add season collumn, maybe use multilevel model.

#1/Site generates random variable, don't need to specify site

Air_Data_NC$Season <- ifelse(Air_Data_NC$Week %in% c(25:34), "SUMMER",
                    ifelse (Air_Data_NC$Week %in% c(35:51), "AUTUMN",ifelse (Air_Data_NC$Week %in% c(52, 53, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), 
                                    "WINTER", "SPRING")))

Air_Data_NC$Season <- factor(Air_Data_NC$Season,
                             levels=( c("SUMMER", "AUTUMN", "WINTER", "SPRING")))

Air_Data_NC$SITE_ID <- factor(Air_Data_NC$SITE_ID,
                              levels=(c("Beaufort", "Candor", "Coweeta","Cranberry","Duke Forest")))

#lmer (concentration ~ Season + Year + 1|SITE_ID,
#      data=df)

lmtest <- lm(SO4 ~ Season + Year, data=Air_Data_NC)
summary(lmtest)
plot(lmtest)

ggplot(Air_Data_NC) +
  geom_boxplot(aes(x=SITE_ID, y=SO4)) +
  geom_jitter(aes(x=SITE_ID, y=SO4))


lmm1 <- lmer(SO4 ~ Season + Year + (1|SITE_ID), data=Air_Data_NC)
AIC(lmm1) #Only gas with normal AIC
plot(lmm1)
qqnorm(resid(lmm1)) 
summary(lmm1) #Lower in Winter and Autumn than in summer. Decreasing over time in the target years. 

lmm2 <- lmer(NO3 ~ Season + Year + (1|SITE_ID), data=Air_Data_NC)
AIC(lmm2)
plot(lmm2)
qqnorm(resid(lmm2)) 
summary(lmm2) #Autumn, winter, and spring all have significantly higher concentrations than in summer. 

lmm3 <- lmer(HNO3 ~ Season + Year + (1|SITE_ID), data=Air_Data_NC)
AIC(lmm3)
plot(lmm3)
qqnorm(resid(lmm3)) 
summary(lmm3) #Shows concentrations are significantly higher in winter and spring than summer

lmm4 <- lmer(NH4 ~ Season + Year + (1|SITE_ID), data=Air_Data_NC)
AIC(lmm4)
plot(lmm4)
qqnorm(resid(lmm4)) 
summary(lmm4) #Autumn has strong significance, lower concentrations from Summer. It has also been getting lower over the target years. 

#Can say which gases have seasonal effects

```



```{r}
#Brock's linear regression work

#I want to use week as a proxy for time of year as a predictor of air concentration of whatever gas. I want to convert the week value (1-52) into a sin and cosine wave transformation so that it fits for seasonality and is not treated as a linear variable which would not make sense here (week 52 is close to week 1 and summer is in the middle). 

#Will do like Y = B0 + B1 sin(2pi*week / 52) + B2 cos(2pi*week / 52) + B3 + B4 + E. Thinking to use concentration of another gas as another predictor and also maybe site ID as a factor, though that might be overfitting. 

Air_Data_NC <- Air_Data_NC %>% 
  mutate(
    sin_week = sin(2 * pi * Week / 52),
    cos_week = cos(2 * pi * Week / 52)
  )

ggplot(Air_Data_NC, aes(x = Week)) +
  geom_line(aes(y = sin_week, color = "Sine"), size = 1) +
  geom_line(aes(y = cos_week, color = "Cosine"), size = 1) 


#checking some quick plots to look for correlation in gas concentrations
SO4_NO3 <- ggplot(Air_Data_NC, aes(x = NO3, y = SO4))+
  geom_point()
print(SO4_NO3)
#definitely a decent positive correlation

SO4_HNO3 <- ggplot(Air_Data_NC, aes(x = HNO3, y = SO4))+
  geom_point()
print(SO4_HNO3)
#also pretty decent positive correlation. A little more scattered than previous

SO4_NH4 <- ggplot(Air_Data_NC, aes(x = NH4, y = SO4))+
  geom_point()
print(SO4_NH4)
#really strong correlation!

#trying out a basic first model
lm1 <- lm(SO4 ~ sin_week + cos_week + NH4, data = Air_Data_NC)
summary(lm1)
#this is already a really strong fit and statistically significant
```






