---
title: "Lab5"
author: "Brock Keller"
date: "2025-02-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(dplyr)
library(tidyverse)
library(moments)
library(ggplot2)
library(lubridate)
library(readxl)
library(FSA)
```
what is your favorite food? 

pizza
burritos
sushi

```{r}
#NC air data from EPA
Air_Data_NC <- read.csv("NC_Air_Data_Project.csv")

```


```{r}
#making a plot for first assignment
#annual range in concentrations of select chemical in each site

#setting concentrations to be numeric

Air_Data_NC <- Air_Data_NC %>% 
  mutate(across(c(Week, Year, Ca, Cl, HNO3, HNO3.PPB, K, Mg, Na, NH4, NO3, SO2, SO2.PPB, SO4, TNO3,), as.numeric))

#filtering for just 2023
Air_Data_2023 <- Air_Data_NC %>% 
  filter(Year == "2023")

#checking how variables are stored. Looks good
str(Air_Data_2023$SO4)

#grouping by SITE_ID and getting summary statistics
Air_Summary_2023 <- Air_Data_2023 %>% 
  group_by(SITE_ID) %>% 
  summarize(mean = mean(SO4, na.rm = TRUE),
            sd = sd(SO4, na.rm = TRUE)) %>% 
  ungroup()

#making plot
SO4_2023_plot <- ggplot()+
  geom_errorbar(data = Air_Summary_2023, na.rm = TRUE,
                aes(x = SITE_ID, 
                    ymin = mean - sd,
                    ymax = mean + sd,
                    color = SITE_ID),
                width = 0.1, size = 1)+
  geom_jitter(data = Air_Data_2023, na.rm = TRUE,
              aes(x = SITE_ID, y = SO4, 
                  color = SITE_ID),
              alpha = 0.8, size = 0.5)+
  geom_point(data = Air_Summary_2023, na.rm = TRUE,
             aes(x = SITE_ID, y = mean,
                 color = SITE_ID),
             SIZE = 3)+
  labs(title = "Concentrations of SO4 by Site in 2023",
       x = "Site",
       y = "SO4")+
  theme_bw()

print(SO4_2023_plot)

```












